ignored = ["github.com/Sirupsen/logrus"]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.5"

[[constraint]]
  name = "k8s.io/api"
  revision = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/client-go"
  revision = "kubernetes-1.10.0"

[[constraint]]
  name = "github.com/mesosphere/dcos-edge-lb"
  revision = "6dda6613635a600cd7b6471784dbab9d04d805b0" # PR 130