apiVersion: v1
kind: Service
metadata:
  labels:
    app: dklb
  name: dklb
  namespace: kube-system
spec:
  selector:
    app: dklb
  ports:
  - name: admission
    port: 443
    targetPort: 8443
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dklb
  name: dklb
  namespace: kube-system
spec:
  priorityClassName: system-node-critical
  containers:
  - name: dklb
    image: mesosphere/dklb
    imagePullPolicy: Always
    args:
    - /dklb
    - --pod-namespace
    # NOTE: Populated from the "downward API".
    - "$(POD_NAMESPACE)"
    - --pod-name
    # NOTE: Populated from the "downward API".
    - "$(POD_NAME)"
    - --kubernetes-cluster-framework-name
    # NOTE: Populated from the "kube-system/mke-cluster-info" configmap.
    - "$(CLUSTER_NAME)"
    - --log-level
    - trace
    - --tls-cert-file
    - /tls/tls.crt
    - --tls-private-key-file
    - /tls/tls.key
    ports:
    - name: admission
      containerPort: 8443
    - name: metrics
      containerPort: 10250
    readinessProbe:
      httpGet:
        path: /healthz
        port: admission
        scheme: HTTPS
    envFrom:
    - configMapRef:
        name: mke-cluster-info
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      requests:
        memory: "64Mi"
        cpu: "10m"
    volumeMounts:
    - name: dklb-tls
      mountPath: /tls
      readOnly: true
  serviceAccountName: dklb
  volumes:
  - name: dklb-tls
    secret:
      secretName: dklb-tls
