apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dklb
  name: dklb
  namespace: kube-system
spec:
  containers:
  - name: dklb
    image: mesosphere/dklb
    imagePullPolicy: Always
    args:
    - /dklb
    - --debug
    - --pod-namespace
    # NOTE: Populated from the "downward API".
    - "$(POD_NAMESPACE)"
    - --pod-name
    # NOTE: Populated from the "downward API".
    - "$(POD_NAME)"
    - --kubernetes-cluster-framework-name
    # NOTE: Populated from the "kube-system/mke-cluster-info" configmap.
    - "$(CLUSTER_NAME)"
    envFrom:
    - configMapRef:
        name: mke-cluster-info
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  # WARNING: Requires the "docker-hub" secret to be present in the "kube-system" namespace beforehand.
  # This secret must contain credentials to access the "mesosphere/dklb" Docker Hub repository.
  imagePullSecrets:
    - name: docker-hub
  serviceAccountName: dklb
