apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dklb
  name: dklb
  namespace: kube-system
spec:
  priorityClassName: system-node-critical
  containers:
  - name: dklb
    image: mesosphere/dklb
    imagePullPolicy: Always
    args:
    - /dklb
    - --debug
    - --pod-namespace
    # NOTE: Populated from the "downward API".
    - "$(POD_NAMESPACE)"
    - --pod-name
    # NOTE: Populated from the "downward API".
    - "$(POD_NAME)"
    - --kubernetes-cluster-framework-name
    # NOTE: Populated from the "kube-system/mke-cluster-info" configmap.
    - "$(CLUSTER_NAME)"
    ports:
    - containerPort: 10250
    envFrom:
    - configMapRef:
        name: mke-cluster-info
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      requests:
        memory: "64Mi"
        cpu: "10m"
  serviceAccountName: dklb
